apiVersion: v1
kind: Service
metadata:
  name: minecraft-voice-chat
  namespace: minecraft
  labels:
    app: minecraft-server
spec:
  type: LoadBalancer
  ports:
    - name: minecraft
      port: 24454
      targetPort: 24454
      protocol: UDP
  selector:
    app: minecraft-server
